spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&serverTimezone=UTC
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        metadata:
          instance: c
          haha: hehe
          version: v1
        ## 指定nacos server的地址
        server-addr:  localhost:8848
        # 指定namespace
        #        namespace:  4586ae15-e7e6-4a53-bc51-19bcfc691abf
        ## NJ
        # 指定集群名称
        cluster-name:  NJ
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          group: binder-group
  #    stream:
  #      rocketmq:
  #        binder:
  #          name-server: 127.0.0.1:9876
  #       bindings:
  #         input:
  ##           destination: stream-test-topic
  #           destination: add-bonus
  #           group: binder-group
  #         my-input:
  #           destination: stream-my-topic
  #             # 如果用的是RocketMQ, 一定要设置
  #             # 如果用的是其他MQ,可留空
  #             group: my-group
  application:
    ## 服务名称尽量用——,不要用_,不要用特殊字符
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
    #坑 要改为驼峰写法
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率,默认是0.1(10%)
      probability: 1.0
server:
  port: 8081
#rocketmq:
#  name-server: 127.0.0.1:9876
logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug
jwt:
  secret: aaaaabbbbbccccddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
