spring:
  zipkin:
    base-url: http://localhost:9411/
    #坑 要改为驼峰写法
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率,默认是0.1(10%)
      probability: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&serverTimezone=UTC
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        ## 指定nacos server的地址  【服务发现】
        server-addr:  localhost:8848
        cluster-name: BJ
          # 指定namespace
    sentinel:
#      datasource:
#        # 名称随意
#        flow:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-flow-rules
#            groupId: SENTINEL_GROUP
#            # 规则类型，取值见：
#            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
#            rule-type: flow
#        degrade:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-degrade-rules
#            groupId: SENTINEL_GROUP
#            rule-type: degrade
#        system:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-system-rules
#            groupId: SENTINEL_GROUP
#            rule-type: system
#        authority:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-authority-rules
#            groupId: SENTINEL_GROUP
#            rule-type: authority
#        param-flow:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-param-flow-rules
#            groupId: SENTINEL_GROUP
#            rule-type: param-flow
      filter:
        # 打开/关闭 掉对 Spring MVC端点的保护
        enabled: true
      transport:
#         指定sentinel 控制台地址
        dashboard:  localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          # 用来指定topic
          destination: add-bonus
#    stream:
#      rocketmq:
#        binder:
#          name-server: 127.0.0.1:9876
#        bindings:
#          output:
#            producer:
#              #实现事务 -> transactional 、group
#              transactional: true
#              group: tx-add-bonus-group
#      bindings:
#        output:
##          destination: stream-test-topic
#          destination: add-bonus
#          # 如果用的是RocketMQ, 一定要设置
#          # 如果用的是其他MQ,可留空
#          group: binder-group
#        my-output:
#          destination: stream-my-topic
#            # 如果用的是RocketMQ, 一定要设置
#            # 如果用的是其他MQ,可留空
#            group: my-group


  main:
    allow-bean-definition-overriding: true
server:
  port: 8010
#user-center:
#  ribbon:
### 开启饥饿加载模式
ribbon:
  eager-load:
    enabled:  true
    #为哪些名称的服务开启饥饿加载
    clients: user-center
logging:
  level:
    com.itmuch.contentcenter.configuration.UserCenterConfiguration: debug
    com.alibaba.nacos: error
feign:
  sentinel:
    # 开启 sentinel 支持
    enabled: true
  client:
    config:
      #全局打印日志
      default :
        loggerLevel : full
        requestInterceptors:
          - com.itmuch.contentcenter.feignclient.interceptor.TokenRelayRequestIntecepor
  httpclient:
    # 让feign使用apache httpclient做请求，而不是默认的urlconnection
    enabled: true
    # feign的最大链接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 熔断
management:
  endpoints:
    web:
      exposure:
        include: '*'
resttemplate:
  sentinel:
    # 关闭@SentinelRestTemplate注解
    enabled: false

#ahas.namespace: default
#project.name: content-center
#ahas.license: 784c737830e3449a9e9556556adeb282

#rocketmq:
#  name-server:  127.0.0.1:9876
#  producer:
#    # 小坑  必须指定group
#    group:  test-group

jwt:
  secret: aaaaabbbbbccccddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
mybatis:
  configuration:
    map-underscore-to-camel-case: true
