# Yet Anther Markup  Language(.yml/.yaml) ==>JSON子集

#所有环境公用的配置属性
management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      base-path: /metrics,/health
info:
  app: spring-boot-demo
  author: damu
  email: xxx@email

#连字符
spring:
  profiles:
    active: dev
---
# profile=x的专用属性,也就是某个环境下的专用属性
# 开发环境
spring:
  profiles: dev
---
# profile=y的专用属性,也就是某个环境下的专用属性
# 生产环境
---
spring:
  profiles: prod
server:
  tomcat:
    max-connections: 1000
    max-threads: 300
